name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate Readme
        run: node commands/createReadme.js

      - name: Configure Git User
        run: |
          git config user.email "laryssamagal@gmail.com"
          git config user.name "laryssamagalhaes"

      - name: Commit Readme changes
        run: |
          git add README.md
          git diff --staged --quiet || git commit -m 'feat(Readme) add new speaker :)'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
